### PR TITLE
Bump upload-artifact and download-artifact version to v3

### PR DESCRIPTION
**Pull request by InfinityWei**
The failure error for Action [#291](https://github.com/clangd/clangd/actions/runs/10763325232) indicates that GitHub has completely deprecated the v1 and v2 versions of `upload-artifact` and `download-artifact`.
This pull request bumps their versions to v3 to workaround failures.

### CODE REVIEW

**Comment by InfinityWei** [comment]
> The failure error for Action [#291](https://github.com/clangd/clangd/actions/runs/10763325232) indicates that GitHub has completely deprecated the v1 and v2 versions of `upload-artifact` and `download-artifact`. This pull request bumps their versions to v3 to workaround failures.

Additionally, perhaps we should fork these repository with the currently available version to prevent the problems caused by the deprecation of these actions.

**Comment by HighCommander4** [comment]
> Additionally, perhaps we should fork these repository with the currently available version to prevent the problems caused by the deprecation of these actions.

I think, as long as these sorts of breaking changes are not too frequent, it's probably better to stay up to date with the upstream actions, since they probably make security and performance improvements over time.

By the way, do you know if there is a way to subscribe to notifications about failed workflows? I'd like to learn about failures when they occur.

**Comment by InfinityWei** [comment]
> > Additionally, perhaps we should fork these repository with the currently available version to prevent the problems caused by the deprecation of these actions.
> 
> I think, as long as these sorts of breaking changes are not too frequent, it's probably better to stay up to date with the upstream actions, since they probably make security and performance improvements over time.
> 
> By the way, do you know if there is a way to subscribe to notifications about failed workflows? I'd like to learn about failures when they occur.

Yes, staying up to date is best, but I found that once we upgrade to v4, it won’t run on version 18.04 due to the glibc version issue, unless we consider dropping support for 18.04 just like VSCode.

You can see the full logs of my actions failures in [My fork's Build release binaries #23](https://github.com/InfinityWei/clangd/actions/runs/10814594694/job/30001455126)
The key errors are as follows:
```shell
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

Regarding subscribing to notifications for workflow failures, to my knowledge, it might be in the Notifications page under the repo settings, you can have a try.
notification

**Comment by HighCommander4** [comment]
I manually triggered a snapshot release, seems to be working now: https://github.com/clangd/clangd/releases/tag/snapshot_20240913 -- thanks again!

> I found that once we upgrade to v4, it won’t run on version 18.04 due to the glibc version issue, unless we consider dropping support for 18.04 just like VSCode.
> 
> You can see the full logs of my actions failures in [My fork's Build release binaries #23](https://github.com/InfinityWei/clangd/actions/runs/10814594694/job/30001455126) The key errors are as follows:
> 
> ```shell
> /__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
> ```

Ok, let's re-evaluate if/when v3 is deprecated. If at that time we still want to keep the 18.04 support, we can fork the v3 action to keep it working.

**Pull request merged**
