### PR TITLE
Upgrade to ubuntu 20.04 and update package information

### PR DESCRIPTION
**Pull request by usx95**
See https://github.com/actions/runner-images/issues/6002

### CODE REVIEW

**Comment by usx95** [comment]
Temporarily removed upload tests to test for compatibility:
Status/Progress: https://github.com/usx95/clangd/actions/runs/4617853806/jobs/8164598547

**Comment by usx95** [comment]
Update: I do not think we can upgrade this to 20.04 as in this PR.
https://github.com/usx95/clangd/actions/runs/4617853806/jobs/8164598547 fails at the `binary compatibility` stage.

**Comment by sam-mccall** [comment]
Ouch :-(
pthread_cond_clockwait is a really new symbol, glibc 2.30, and that would break compatibility with a lot of systems.

OTOH it's not clear how to avoid using it, i don't think we're supposed to try to override `_GLIBCXX_USE_PTHREAD_COND_CLOCKWAIT`.

Maybe it's necessary to build inside a docker container now :-(
https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

**Comment by sam-mccall** [comment]
delorted

**Pull request closed without merging**
