### PR TITLE
Modernize CI

### PR DESCRIPTION
**Pull request by wusatosi**
This PR updates the auto-build CI pipeline.
Specifically:
1. Updates actions/checkout
2. Updates `actions/upload-artifact`, `actions/download-artifact` and resolves the breaking change.
3. Replaces discontinued `actions/create-release` and `actions/upload-release-asset` with the GitHub CLI

Successful test on latest commit:
https://github.com/wusatosi/clangd/actions/runs/4874186461

Generated release:
https://github.com/wusatosi/clangd/releases/tag/ci-test-12

Edit: Please review @kadircet @usx95 @sam-mccall

### CODE REVIEW

**Comment by wusatosi** [comment]
Question for maintainer: 
https://github.com/clangd/clangd/blob/6e7f5968bae8076cc5a4a751af061e71bbb3e32f/.github/workflows/autobuild.yaml#L5-L6

Unless one job takes over 24 hours to complete, this is not true, ["Before each job begins, GitHub fetches an installation access token for the job. The GITHUB_TOKEN expires when a job finishes or after a maximum of 24 hours."](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)

Should I replace the `RELEASE_TOKEN` with `GITHUB_TOKEN` of appropriate permissions?

**Comment by wusatosi** [comment]
Currently testing on: https://github.com/wusatosi/clangd/actions/runs/4874186461

Should be ready if it passes.

**Review by aaronmondal — CHANGES_REQUESTED** [review]
@wusatosi I've messaged you on Discord.

**Comment by aaronmondal** [comment]
According to OpenSSF security best practices it's generally a good idea to use explicit commit hashes to ensure that the actions themselves are reproducible and robust against malicious activity in the upstream action repos.

See https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies for reasoning. However, I believe this is under the assumption that one has bots tracking these hashes and triggering automatic hash updates. In any case I think it's worth considering.

The OpenSSF also recommends globally setting explicit `read-all` permissions for every action globally that are only elevated locally for specific steps: https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

 I've just encountered this myself, here is how a pinned version could look like: https://github.com/eomii/rules_ll/commit/c927b8090011e33a47c624bf8b63504b57abfb96 (that repo is crawled by dependabot and renovate though).
 
 Here is how explicit permissions could look like: https://github.com/eomii/rules_ll/commit/4734461ca5a47f71a21dad41e07d3ee91e7d51de
 
 My comments are not specific to this particular PR, and more so with the workflows in clangd in general, so feel free to ignore it for the sake of this PR.

**Comment by aaronmondal** [comment]
@kadircet Would you mind taking a look?

**Comment by kadircet** [comment]
sorry for shying away from this review for a while now. any chance you can split those into different changes, updates of  `actions/checkout`, `actions/upload-artifact`, `actions/download-artifact` look safe and trivial.

i am not so sure about the change to `wusatosi/setup-gh@v1`. Why not use https://github.com/softprops/action-gh-release but come up with a new action?

re @aaronmondal, sure using actions from explicit hashes instead of tags makes sense. feel free to send a follow-up patch if @wusatosi don't do that already.

**Comment by aaronmondal** [comment]
@kadircet Thanks for taking a look!

I agree that `softprops/action-gh-release` seems like a better choice since it seems to be the most widely used release action.

**Comment by wusatosi** [comment]
> sorry for shying away from this review for a while now. any chance you can split those into different changes, updates of `actions/checkout`, `actions/upload-artifact`, `actions/download-artifact` look safe and trivial.
> 
> i am not so sure about the change to `wusatosi/setup-gh@v1`. Why not use https://github.com/softprops/action-gh-release but come up with a new action?
> 
> re @aaronmondal, sure using actions from explicit hashes instead of tags makes sense. feel free to send a follow-up patch if @wusatosi don't do that already.

Hi, thanks for looking over this pr, I am in the middle of final exams and will update this pr once I have time.

**Comment by wusatosi** [comment]
closing this right now as its out-of-date

**Pull request closed without merging**
